In [20]:
import cv2
import numpy as np

In [21]:
img1 = cv2.imread('dataset/test/true/0_10671.jpg')
img2 = cv2.imread('dataset/test/true/0_10672.jpg')

In [22]:
print(img1)

[[[11 11 11]
  [10 10 10]
  [ 9  9  9]
  ...
  [12 12 12]
  [13 13 13]
  [14 14 14]]

 [[10 10 10]
  [10 10 10]
  [ 9  9  9]
  ...
  [11 11 11]
  [12 12 12]
  [12 12 12]]

 [[10 10 10]
  [10 10 10]
  [10 10 10]
  ...
  [11 11 11]
  [11 11 11]
  [11 11 11]]

 ...

 [[59 59 59]
  [59 59 59]
  [59 59 59]
  ...
  [42 42 42]
  [34 34 34]
  [32 32 32]]

 [[59 59 59]
  [59 59 59]
  [59 59 59]
  ...
  [41 41 41]
  [33 33 33]
  [32 32 32]]

 [[59 59 59]
  [58 58 58]
  [58 58 58]
  ...
  [40 40 40]
  [32 32 32]
  [33 33 33]]]


In [23]:
for x in img1:
    print(x, x.shape, img1.shape)
    break

[[11 11 11]
 [10 10 10]
 [ 9  9  9]
 ...
 [12 12 12]
 [13 13 13]
 [14 14 14]] (640, 3) (640, 640, 3)


In [24]:
# Create an output image
output = img1.copy()

# Loop through each pixel and compare color values
for y in range(img1.shape[0]):
    for x in range(img1.shape[1]):
        if not np.array_equal(img1[y, x], img2[y, x]):
            output[y, x] = [0, 0, 255]  # Set pixel to red

# Display or save the result
cv2.imshow('Differences Highlighted', output)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [46]:
# Calculate absolute difference between the images
diff = cv2.absdiff(img1, img2)

# Threshold the differences to create a binary mask
threshold = 10  # You can adjust this threshold value

# Create a binary mask based on color differences
mask = np.zeros_like(diff)
total_pixels = diff.shape[0] * diff.shape[1]
differing_pixels = np.count_nonzero(np.any(diff > threshold, axis=2))
mask[(diff >= threshold).any(axis=2)] = [0, 0, 255]

# Add the mask to the original image to highlight differences
highlighted = cv2.addWeighted(img1, 1, mask, 0.5, 0)

difference_percentage = (differing_pixels / total_pixels) * 100

print(f"Differences: {differing_pixels} pixels")
print(f"Total pixels: {total_pixels} pixels")
print(f"Difference Percentage: {difference_percentage:.2f}%")

# Display or save the result
# cv2.imshow('Differences Highlighted', highlighted)
# cv2.waitKey(0)
# cv2.destroyAllWindows()

Differences: 438 pixels
Total pixels: 409600 pixels
Difference Percentage: 0.11%
