In [50]:
import csv
import numpy as np
from keras.models import Sequential
from keras.layers import Dense, Embedding, Dropout, LSTM
from keras.callbacks import ModelCheckpoint
from keras.utils import np_utils
import tensorflow as tf

In [51]:
with open('data_clean.csv', newline='') as f:
    reader = csv.reader(f)
    data = list(reader)

In [52]:
X_train = []
Y_train = []
X_test = []
Y_test = []
# ALL = 42325 Train 33860 Test 8465 minus 4
train_count = int((len(data) - 16) * 0.8)
test_count = len(data) - train_count - 4
print(train_count, test_count)
frame_size = 25

33850 8475


In [53]:
y_history = {'true': 0, 'false': 0}

for i, x in enumerate(data[:train_count]):
    X_train.append(float(x[1]))
    if x[3]:
        y_history['true'] += 1
    else:
        y_history['false'] += 1

    if i % frame_size == 0:
        Y_train.append(y_history['true'] > y_history['false'])
        y_history = {'true': 0, 'false': 0}

y_history = {'true': 0, 'false': 0}
print(len(data), len(data[train_count:test_count]), train_count, test_count)
for i, x in enumerate(data[train_count: train_count + test_count]):
    X_test.append(float(x[1]))
    if x[3]:
        y_history['true'] += 1
    else:
        y_history['false'] += 1

    if i % frame_size == 0:
        Y_test.append(y_history['true'] > y_history['false'])
        y_history = {'true': 0, 'false': 0}

print(len(X_test), len(Y_test))

X_train = np.array(X_train)
Y_train = np.array(Y_train)
X_test = np.array(X_test)
Y_test = np.array(Y_test)

# e = int(X_train.shape[0] / 25)
X_train = X_train.reshape((int(train_count / frame_size), frame_size, 1))
X_test = X_test.reshape((int(test_count / frame_size), frame_size, 1))
print(X_train.shape, Y_train.shape, X_test, Y_test)





42329 0 33850 8475
8475 339
(1354, 25, 1) (1354,) [[[0.06]
  [0.06]
  [0.06]
  ...
  [0.06]
  [0.06]
  [0.06]]

 [[0.06]
  [0.06]
  [0.06]
  ...
  [0.06]
  [0.06]
  [0.06]]

 [[0.06]
  [0.06]
  [0.06]
  ...
  [0.06]
  [0.06]
  [0.06]]

 ...

 [[0.04]
  [0.04]
  [0.04]
  ...
  [0.04]
  [0.04]
  [0.04]]

 [[0.04]
  [0.04]
  [0.04]
  ...
  [0.06]
  [0.06]
  [0.06]]

 [[0.06]
  [0.06]
  [0.06]
  ...
  [0.04]
  [0.04]
  [0.04]]] [ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True 

## Definicja modelu

In [54]:
model = Sequential()
model.add(LSTM(3, input_shape=(25, 1), dropout=0.2) )
# model.add(Dropout(0.2))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['binary_accuracy', tf.keras.metrics.TruePositives(), tf.keras.metrics.TrueNegatives()])

In [55]:
model.fit(X_train, Y_train, validation_data=(X_test, Y_test), epochs=10)

Epoch 1/10
43/43 [==============================] - 7s 154ms/step - loss: 0.5628 - binary_accuracy: 0.9690 - true_positives_4: 1312.0000 - true_negatives_3: 0.0000e+00 - val_loss: 0.5590 - val_binary_accuracy: 1.0000 - val_true_positives_4: 339.0000 - val_true_negatives_3: 0.0000e+00
Epoch 2/10
43/43 [==============================] - 4s 91ms/step - loss: 0.4100 - binary_accuracy: 1.0000 - true_positives_4: 1354.0000 - true_negatives_3: 0.0000e+00 - val_loss: 0.4460 - val_binary_accuracy: 1.0000 - val_true_positives_4: 339.0000 - val_true_negatives_3: 0.0000e+00
Epoch 3/10
43/43 [==============================] - 4s 91ms/step - loss: 0.2940 - binary_accuracy: 1.0000 - true_positives_4: 1354.0000 - true_negatives_3: 0.0000e+00 - val_loss: 0.3323 - val_binary_accuracy: 1.0000 - val_true_positives_4: 339.0000 - val_true_negatives_3: 0.0000e+00
Epoch 4/10
43/43 [==============================] - 4s 93ms/step - loss: 0.1992 - binary_accuracy: 1.0000 - true_positives_4: 1354.0000 - true_nega